import Company from "@/interfaces/Company";

const companies: Company[] = [
    {
        name: "Work Solutions",
        cities: ["Ростов-на-Дону"],
        markets: ["1111", "2222"],
        domainExpertise: ["dfsaf", "dsafds"],
        employeesNumber: 40,
        cooperationFormat: ["Аутсорсинг", "Аутстаффинг"],
        technologiesStack: ["PHP", "Laravel", "Symphony", "React", "Vue"],
        services: ["Frontend", "Backend"],
        sorting: 13,
        activity: true,
        isMember: true,
        site: "https://worksolutions.ru/",
        isBroker: false,
        isAccredited: true,
        rusProfileLink: "fdsfdsdsd",
        contacts: "Артем Салютин CBDO",
        servicesDescription: "fsdfsd",
        marketsDescription: "dddddddd",
        queryShowcase: "eeeeeeeee",
        queryShowcaseDescription: "22222eeeeeerwew",
        domainExpertiseDescription: "ddddddddgggggggfrgfd",
        benchCard: "https://docs.google.com/spreadsheets/d/1MBkuMDgl_BqadUh9UheLKvmIwsGMuzvHeiw6kKMM4r4/edit#gid=0",
        benchCardDescription: "dddddd",
        contentArea: "dddddssssfasd",
        industrialDevelopments: "PHP-коллекции, конфигуриремая административная панель",
    },
    {
        name: "Work Solutions",
        cities: ["Ростов-на-Дону"],
        markets: ["1111", "2222"],
        domainExpertise: ["dfsaf", "dsafds"],
        employeesNumber: 40,
        cooperationFormat: ["Аутсорсинг", "Аутстаффинг"],
        technologiesStack: ["PHP", "Laravel", "Symphony", "React", "Vue"],
        services: ["Frontend", "Backend"],
        sorting: 13,
        activity: true,
        isMember: true,
        site: "https://worksolutions.ru/",
        isBroker: true,
        isAccredited: true,
        queryShowcaseDescription: "22222eeeeeerwew",
        domainExpertiseDescription: "ddddddddgggggggfrgfd",
        benchCard: "https://docs.google.com/spreadsheets/d/1MBkuMDgl_BqadUh9UheLKvmIwsGMuzvHeiw6kKMM4r4/edit#gid=0",
        benchCardDescription: "dddddd",
        contentArea: "dddddssssfasd",
        industrialDevelopments: "PHP-коллекции, конфигуриремая административная панель",
    },
    {
        name: "Work Solutions",
        cities: ["Ростов-на-Дону"],
        markets: ["1111", "2222"],
        domainExpertise: ["dfsaf", "dsafds"],
        employeesNumber: 40,
        cooperationFormat: ["Аутсорсинг"],
        technologiesStack: ["PHP", "Laravel", "Symphony", "React", "Vue"],
        services: ["Frontend", "Backend"],
        sorting: 13,
        activity: true,
        isMember: true,
        site: "https://worksolutions.ru/",
        isBroker: false,
        isAccredited: true,
        benchCard: "https://docs.google.com/spreadsheets/d/1MBkuMDgl_BqadUh9UheLKvmIwsGMuzvHeiw6kKMM4r4/edit#gid=0",
        benchCardDescription: "dddddd",
        contentArea: "dddddssssfasd",
        industrialDevelopments: "PHP-коллекции, конфигуриремая административная панель",
    },
    {
        name: "Work Solutions",
        cities: ["Ростов-на-Дону"],
        markets: ["1111", "2222"],
        domainExpertise: ["dfsaf", "dsafds"],
        employeesNumber: 40,
        cooperationFormat: ["Аутсорсинг", "Аутстаффинг"],
        technologiesStack: ["PHP", "Laravel", "Symphony", "React", "Vue"],
        services: ["Frontend", "Backend"],
        sorting: 13,
        activity: true,
        isMember: true,
        site: "https://worksolutions.ru/",
        isBroker: false,
        isAccredited: true,
        rusProfileLink: "fdsfdsdsd",
        benchCardDescription: "dddddd",
        contentArea: "dddddssssfasd",
        industrialDevelopments: "PHP-коллекции, конфигуриремая административная панель",
    },
    {
        name: "Work Solutions",
        cities: ["Ростов-на-Дону"],
        markets: ["1111", "2222"],
        domainExpertise: ["dfsaf", "dsafds"],
        employeesNumber: 40,
        cooperationFormat: ["Аутстаффинг"],
        technologiesStack: ["PHP", "Laravel", "Symphony", "React", "Vue"],
        services: ["Frontend", "Backend"],
        sorting: 13,
        activity: true,
        isMember: true,
        site: "https://worksolutions.ru/",
        isBroker: false,
        isAccredited: true,
        rusProfileLink: "fdsfdsdsd",
        contacts: "Артем Салютин CBDO",
        servicesDescription: "fsdfsd",
        marketsDescription: "dddddddd",
        queryShowcase: "eeeeeeeee",
        queryShowcaseDescription: "22222eeeeeerwew",
        domainExpertiseDescription: "ddddddddgggggggfrgfd",
        benchCard: "https://docs.google.com/spreadsheets/d/1MBkuMDgl_BqadUh9UheLKvmIwsGMuzvHeiw6kKMM4r4/edit#gid=0",
    },
    {
        name: "Work Solutions",
        cities: ["Ростов-на-Дону"],
        markets: ["1111", "2222"],
        domainExpertise: ["dfsaf", "dsafds"],
        employeesNumber: 40,
        cooperationFormat: ["Аутсорсинг", "Аутстаффинг"],
        technologiesStack: ["PHP", "Laravel", "Symphony", "React", "Vue"],
        services: ["Frontend", "Backend"],
        sorting: 13,
        activity: true,
        isMember: false,
        site: "https://worksolutions.ru/",
        isBroker: false,
        queryShowcase: "eeeeeeeee",
        queryShowcaseDescription: "22222eeeeeerwew",
        domainExpertiseDescription: "ddddddddgggggggfrgfd",
        benchCard: "https://docs.google.com/spreadsheets/d/1MBkuMDgl_BqadUh9UheLKvmIwsGMuzvHeiw6kKMM4r4/edit#gid=0",
        benchCardDescription: "dddddd",
        contentArea: "dddddssssfasd",
        industrialDevelopments: "PHP-коллекции, конфигуриремая административная панель",
    },
];

export default companies;