export default interface Company {
    name: string,
    cities: string[],
    markets: string[],
    domainExpertise: string[],
    employeesNumber: number,
    cooperationFormat: string[],
    technologiesStack: string[],
    services: string[],
    sorting: number,
    site?: string,
    isMember?: Boolean,
    isBroker?: Boolean,
    isAccredited?: Boolean,
    rusProfileLink?: string,
    contacts?: string,
    servicesDescription?: string,
    marketsDescription?: string,
    queryShowcase?: string,
    queryShowcaseDescription?: string,
    domainExpertiseDescription?: string,
    benchCard?: string,
    benchCardDescription?: string,
    contentArea?: string,
    industrialDevelopments?: string,
    activity?: boolean,
}